### ISSUE TITLE
Scrollbar makes content too wide when it appears in v. 7.2.1-beta.0 when creating project with  --aot 

### ISSUE THREAD

**Issue by habundes** [MurhafSousli/ngx-scrollbar#280] opened 2020-03-27 16:06 UTC
#### Reproduction

Same as #266 but this time when building project --aot the fix is not reflecting in the list

- Angular: 9.0.6
- ngx-scrollbar: 7.02.1-beta.0
- Browser(s): Chrome/Firefox/Safari

![Issue-1_LI](https://user-images.githubusercontent.com/2348161/77801127-d78ed700-703d-11ea-9be3-8a0d1ffddbca.jpg)

![Issue-2_LI (2)](https://user-images.githubusercontent.com/2348161/77801145-e1b0d580-703d-11ea-8bdb-64d9e28dfe87.jpg)

**Comment by vpetrusevici** [comment] 2020-03-27 20:08
Strange because my project has aot build and bug didn't appear. (I use appearance="compact" everywhere)

**Comment by habundes** [comment] 2020-03-27 21:08
I added appearance="compact" to each scrollbar still same, (I am using css grid for content inside scrollbar, not sure i that impact in width)

**Comment by MurhafSousli** [comment] 2020-03-28 05:23
@habundes That could impact the content, try using additional wrapper for using css grid

**Comment by habundes** [comment] 2020-03-30 23:56
context has even 2 divs are wrapping it.
div.ng-scroll-content
    div.
        div.
            div --> css grid

**Comment by MurhafSousli** [comment] 2020-03-31 22:09
Can you add a reproduction https://stackblitz.com/edit/ngx-scrollbar

**Comment by habundes** [comment] 2020-04-03 23:38
I created the in stackblitz but no able to save it, I lost what I have added to it but is working on stackblitz, I notice that this I am facing is only on Windows Chrome or FireFox.

I created a list-wrapper component:
<ng-scrollbar #scroll visibility="hover" appearance="compact">
----<ng-content select=".list"></ng-content>
</ng-scrollbar>

What I am passing to component is:
<list-wrapper>
----<div classs="list">
--------<div> //div with css grid: display:grid; grid-template-columns: 10% 70% 20%
------------<div></div> // content
------------<div></div> // content
------------<div></div> // content
---------</div>
----</div>
<list-wrapper>

**Comment by habundes** [comment] 2020-04-06 21:32
Fixed, the problem was the content projection with class name I was using.

**Comment by MurhafSousli** [comment] 2020-04-07 09:55
Good! closing...

**Closed by MurhafSousli** 2020-04-07 09:55 UTC
