### ISSUE TITLE
Production build fails with 'strictNullChecks' compiler option

### ISSUE THREAD

**Issue by kayhanablachim** [MurhafSousli/ngx-scrollbar#219] opened 2019-09-24 13:49 UTC
Bug Report:

Versions
Angular CLI: 8.2.4
Angular: 8.2.4
Ngx-Scrollbar: 6.0.0

I've just added 'strictNullChecks' to my compilerOptions in tsconfig and the following error started to show when building for production:

ERROR in node_modules/ngx-scrollbar/ngx-scrollbar.d.ts.NgScrollbar.html(8,10): Argument of type 'number | null' is not assignable to parameter of type 'number'.
  Type 'null' is not assignable to type 'number'.

I'm guessing it's from the CssVariable pipe that's expecting a number, but might also get null from usage in NgScrollbar.html.

Thanks in advance.

**Comment by armandcolenati** [comment] 2019-09-30 17:20
I have the same issue, the only difference is the Angular version which is 8.3.6

**Comment by kayhanablachim** [comment] 2019-10-01 09:24
@MurhafSousli can you please release a new version with this fix?

**Comment by MurhafSousli** [comment] 2019-10-01 11:52
Will do ASAP

**Comment by dsebastien** [comment] 2019-11-19 19:07
I have the same issue with 7.0.2. Could it be cause by the version of Angular (8.2.5) or TypeScript (3.5.3) that I'm using?

**Comment by MurhafSousli** [comment] 2019-11-21 12:18
I thought #221 was the fix, can you find what is causing this issue? PR's are welcome

**Comment by dsebastien** [comment] 2019-11-24 10:01
I'm trying to figure this out.

Here's the error that I'm seeing: 
```
ERROR in node_modules/ngx-scrollbar/ngx-scrollbar.d.ts.NgScrollbar.html(7,10): Argument of type 'number | null' is not assignable to parameter of type 'number | undefined'.
  Type 'null' is not assignable to type 'number | undefined'.
```

**Comment by MurhafSousli** [comment] 2019-11-24 12:37
@dsebastien Try to change `undefined` to `null` and see if it works, that could be it!

**Comment by dsebastien** [comment] 2019-11-24 13:18
I'll continue our discussion here (cfr https://twitter.com/MurhafSousli/status/1198581933464313857).

Indeed, a value is defined through the default options, but since the property is optional and could be overriden through the custom default options, the compiler just doesn't know.

I'm actually trying to build the library using the strictNullChecks option to see where the issue truly lies (because I assume that there are multiple ones).

I've pushed my current changes here: https://github.com/dsebastien/ngx-scrollbar

If you clone that, npm install and run `npm run build-demo`, you'll see the issue.

I've fixed all the other issues that arose after enabling `strictNullChecks` and some other TS options.

**Comment by dsebastien** [comment] 2019-11-24 13:20
So the remaining issue lies within this line: https://github.com/dsebastien/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/ng-scrollbar.html#L7

Which triggers this error under strictNullChecks:

```
ERROR in projects/ngx-scrollbar/src/lib/ng-scrollbar.html(7,10): Argument of type 'number | null' is not assignable to parameter of type 'number | undefined'.
  Type 'null' is not assignable to type 'number | undefined'.

```

**Comment by dsebastien** [comment] 2019-11-24 13:43
@MurhafSousli yep I think that's it. Stupidly enough I didn't think the cssVariable pipe was part of this project so I was looking around it

**Comment by dsebastien** [comment] 2019-11-24 14:12
I've pushed the fixes, so now my fork builds with strictNullChecks enabled!

**Closed** 2019-11-25 20:36 UTC
Labels: enhancement

**Comment by dsebastien** [comment] 2019-11-26 11:39
I can confirm that 7.1.0 works fine under --prod --aot & strictNullChecks!
