### ISSUE TITLE
Breaks on resize

### ISSUE THREAD

**Issue by ShiftyMcCool** [MurhafSousli/ngx-scrollbar#109] opened 2018-12-12 19:13 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 7

### Versions

This is happening on ngx-scrollbar v3.3.3
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      7.1.1
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

Refer to https://github.com/MurhafSousli/ngx-scrollbar/issues/81
Also:
https://stackblitz.com/edit/angular-material2-issue-mqhr8u

### Desired functionality

On smaller screen sizes, the scrollbar seems to break (revert to vanilla looks) and not change back when resizing again. Though in the StackBlitz template, it might already break when you first load in. You'll have to enlarge the preview window, refresh the preview window and then you'll see it loads properly, though if you shrink the preview window, it reverts back to original state. Console does not show any errors, so I'm unsure what's causing this.

### Mention any other details that might be useful

see Stackblitz

**Comment by MurhafSousli** [comment] 2018-12-12 20:18
Duplicate of #106

**Closed** 2018-12-12 20:47 UTC
Labels: bug
