### ISSUE TITLE
Material table horizontal scroll not working when ngscrollbar is added to the angular component that contains the material table

### ISSUE THREAD

**Issue by jeevanthespark** [MurhafSousli/ngx-scrollbar#395] opened 2021-07-27 07:41 UTC
#### Reproduction

Steps to reproduce:
1. Create material table with more number of columns in angular so that horizontal scroll is enabled.
2. Add ngscrollbar to the start of the component and the horizontal scroll gets removed and makes the width of the page extending to full width of the table.
 
 
#### Expected Behavior

What behavior were you expecting to see?
Horizontal scroll in material table gets replaced with ngscrollbar

#### Actual Behavior

What behavior did you actually see?
Horizontal scroll in material table gets removed and makes the width of the page extending to full width of the table

#### Environment

- Angular: 11
- ngx-scrollbar: 7.6
- Browser(s): Edge chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment] 2021-07-27 10:34
Please add a reproduction somewhere with v7.6.1, the stackblitz may not work because it is currently not fetching the latest version of the package (a bug on their end)

**Comment by jeevanthespark** [comment] 2021-07-27 10:53
The reproduction steps for 7.6.1 are same too. I just now tried it with 7.6.1 and it has the same issues.

**Comment by MurhafSousli** [comment] 2021-07-27 16:06
I will not reproduce it for you, if you want help, you reproduce for yourself. maybe the issue is on your end and I don't have time to reproduce issues for everyone! if you don't add reproduction I will close it

**Comment by jeevanthespark** [comment] 2021-07-27 17:22
Can you please check the Test component in the below stackblitz. The MatTable doesnt work with ng-scrollbar.
[https://stackblitz.com/edit/ngx-scrollbar-l9yj2u](url)

**Comment by MurhafSousli** [comment] 2021-07-27 19:14
This is because ng-scrollbar needs to have a fixed height, you can either set the height manually, or enable the auto height feature which is disabled by default.

`<ng-scrollbar [autoHeightDisabled]="false">`

Here is a [working stackblitz](https://stackblitz.com/edit/ngx-scrollbar-gv4jc3?file=src%2Fapp%2Ftest%2Ftest.component.html)

**Closed by MurhafSousli** 2021-07-27 19:14 UTC
Labels: need: reproduction
