### ISSUE TITLE
Scrollbar is not propagating events

### ISSUE THREAD

**Issue by Nekronik** [MurhafSousli/ngx-scrollbar#242] opened 2019-11-14 11:32 UTC
#### Reproduction

Use [StackBlitz](https://stackblitz.com/edit/ngx-scrollbar-compare-native-auto-height) to reproduce the issue.
(I extended a previous stackblitz to reproduce this issue)

Steps to reproduce:
1. Go to `event propagation` tab
2. Scroll all the scrollbars in both directions
 
 
#### Expected Behavior

Events should be propagated as the native scrollbar does.

#### Actual Behavior

Events are not propagated to parent when:

the direction is not being captured by the inner scrollbar

the direction is the same but the inner scrollbar reached the edge and there is remaining space to be scrolled in the parent

### Additional info

I believe this issue also stops native top level scrollbar from gettings the scroll events, which breaks the pull-down-to-refresh action on touch enabled devices using browsers like google chrome or firefox.

I seen that the demo with `Nested CDK Virtual Scroll Example` the scroll events are propagated apropiately.

#### Environment

- Angular: 8.2.15
- ngx-scrollbar: 7.0.1
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): KDE Neon (Ubuntu based)

**Comment by MurhafSousli** [comment] 2019-11-14 13:58
This is caused by this a CSS `overscroll-behavior: contain contain`, a quick fix:
```
.ng-scroll-viewport {
  overscroll-behavior: unset !important;
}
```

**Comment by Nekronik** [comment] 2019-11-14 14:41
@MurhafSousli 
I have an horizontal scrollbar that the initial content has a specific height but when the server responds the height changes.
I've seen you have added this task `fix: Auto-height should be updated with component update event` to next patch.
Could this behavior be related to the task I just mentioned?

**Comment by MurhafSousli** [comment] 2019-11-14 14:52
@Nekronik This will also be fixed in the next patch https://github.com/MurhafSousli/ngx-scrollbar/projects/3

**Closed** 2019-11-16 19:03 UTC
Labels: bug
