### ISSUE TITLE
CSS var() don't support IE11

### ISSUE THREAD

**Issue by jaffbeto** [MurhafSousli/ngx-scrollbar#153] opened 2019-06-07 11:05 UTC
Please, see this and consider adding the project to support IE11. I like this plugin but "CSS var ()" is not compatible with IE11.

Thank you.

https://stackoverflow.com/questions/46429937/ie11-does-a-polyfill-script-exist-for-css-variables

**Comment by MurhafSousli** [comment] 2019-06-07 20:37
Duplicate of  #120, No plans to support IE11

**Closed by MurhafSousli** 2019-06-07 20:37 UTC
Labels: wontfix
