### ISSUE TITLE
ng-scrollbar inside MatDialog with no height

### ISSUE THREAD

**Issue by fabioemoutinho** [MurhafSousli/ngx-scrollbar#222] opened 2019-10-07 16:25 UTC
#### Reproduction

Steps to reproduce:
1. 
```
<h2 mat-dialog-title>Title</h2>
<ng-scrollbar>
  <div mat-dialog-content>
    ...scrollable content here
  </div>
</ng-scrollbar>
```
 2. Open dialog without specifying height
`this.dialog.open(MyDialogComponent, { disableClose: false });`
 
#### Expected Behavior

What behavior were you expecting to see?
dialog with correct height

#### Actual Behavior

What behavior did you actually see?
elements ng-scrollbar, div.ng-scrollbar-wrapper, div.ng-scroll-viewport-wrapper and div.ns-scroll-offset.ng-scroll-viewport got computed height of 0, even though the div.ng-scroll-content has the expected height
This did not happen before ngx-scrollbar 6.0.0

#### Environment

- Angular: 8.2.8
- Angular Material: 8.2.2
- ngx-scrollbar: 6.0.0
- Browser(s): Chrome 77.0.3865.90
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment] 2019-10-25 11:46
Duplicate of #214

**Closed by MurhafSousli** 2019-10-25 11:46 UTC
