### ISSUE TITLE
Event js browser blocked with 'Angular material', 'ngx-scrollbar' and 'angular2-multiselect-dropdown'

### ISSUE THREAD

**Issue by jaffbeto** [MurhafSousli/ngx-scrollbar#148] opened 2019-05-24 13:11 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```
### Versions

4.2.2

### Repro steps

    "@angular/animations": "7.2.15",
    "@angular/cdk": "7.3.7",
    "@angular/common": "7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/material": "7.3.7",
    "@angular/material-moment-adapter": "7.3.7",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@angular/router": "7.2.15",
    "angular2-multiselect-dropdown": "4.2.2",
    "ngx-scrollbar": "4.2.0",

Here is the demo with the error: https://stackblitz.com/edit/angular-dyea2p?file=app%2Fdialog-content-example-dialog.html

### Mention any other details that might be useful

I have in my project angular material and in a 'mat-dialog' I have implemented for the scrollbar 'ngx-scrollbar' everything perfect.

Now I try to add 'angular2-multiselect-dropdown', and great until I try to select an item from the drop-down.

There is a blockage of the browser due to some events, which I understand are in conflict, although the console does not show any error.

Thank you very much for the help!

**Comment by MurhafSousli** [comment] 2019-05-24 19:04
Closing as duplicate of #146

**Closed by MurhafSousli** 2019-05-24 19:04 UTC
