### ISSUE TITLE
Build error - angular 9.0.3

### ISSUE THREAD

**Issue by elvysmarcos** [MurhafSousli/ngx-scrollbar#272] opened 2020-02-25 22:41 UTC
`ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 910:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 913:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 925:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 928:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 153:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 157:42-59
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 160:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'`

**Comment by persi14** [comment] 2020-02-27 06:18
The problem was solved?

**Comment by elvysmarcos** [comment] 2020-02-27 11:13
This issue has not been resolved.

**Comment by vpetrusevici** [comment] 2020-02-27 15:33
The same issue... #270

**Comment by vpetrusevici** [comment] 2020-02-27 15:33
The same issue... #270

**Comment by vpetrusevici** [comment] 2020-02-27 15:34
The same issue... #270

**Comment by nhustak** [comment] 2020-02-28 16:47
Same issue when I bumped to 9.0.4

**Comment by nullifiedtsk** [comment] 2020-02-28 18:48
same for cdk@9.1.0

**Comment by yogaperdana** [comment] 2020-02-29 08:08
Still getting this issue using `@angular/cdk@9.1.0`

Error messages on build:
```
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 910:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 913:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 925:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 928:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 153:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 157:42-59
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 160:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
```

**Comment by burakodabas** [comment] 2020-03-04 14:08
Unfortunately same issue not solved 😞 

`ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 910:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 913:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 925:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 928:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 153:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 157:42-59
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar-smooth-scroll.js 160:47-64
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'`

Changing angular cdk version is not solution for me. I try 9.1.9 and 9.0.1
Please help

**Comment by rm2kdev** [comment] 2020-03-05 01:32
Same issue here with CDK 9.1.0

**Comment by burakodabas** [comment] 2020-03-05 20:12
Heey I found solution for me. Maybe, this solution help you. 

Step 1: **update package.json file**,    "@angular/cdk": "^9.0.0",
okey.
Step 2: Install manuel angular cdk package.share command; 
**npm i @angular/cdk@9.0.0**

_If you not solution follow another steps;_ 

* rm -rf node_modules directory
* npm cache clear
* update npm latest version
* npm install

**Comment by rm2kdev** [comment] 2020-03-06 00:28
@burakodabas thank you for this, reverting CDK back to 9.0 worked for me, its not a permanent solution but it will get us by for a few weeks until the repo becomes compatible with 9.2

**Comment by vpetrusevici** [comment] 2020-03-10 17:16
It also reproduced with disabled Ivy. But in ngx-scrollbar-demo works good after update... 
![image](https://user-images.githubusercontent.com/40790510/76339967-7d82d780-6303-11ea-9265-558e170d6b3d.png)

**Comment by vpetrusevici** [comment] 2020-03-10 17:31
File with RtlScrollAxisType exists but angular doesn't see it in the build time...
![image](https://user-images.githubusercontent.com/40790510/76341483-ca67ad80-6305-11ea-85c5-c2b8bd2d02b2.png)

**Comment by MurhafSousli** [comment] 2020-03-13 17:59
I am very sorry for late, I have been living without internet at home since I relocated..

Please try version `7.2.1-beta.0`.

The error is fixed by just updating the dependencies, I tested it out and build the project without any errors!

**Closed** 2020-03-13 17:59 UTC
