### ISSUE TITLE
Scroll bar doesn't updates mouse events properly

### ISSUE THREAD

**Issue by Tucaen** [MurhafSousli/ngx-scrollbar#49] opened 2018-07-10 10:50 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> Windows 10.

### Versions
ngx-scrollbar: 2.1.0

### Repro steps
When used in a dropdown popover the scrollbar can't be dragged until it was scrolled via mouse wheel:
![scroll issue](https://user-images.githubusercontent.com/12460448/42505595-7910c760-843f-11e8-9abe-4285e7b51d2e.gif)

### Desired functionality
Be scrollable via mouse drag without the need of an initial scroll via mouse wheel.

**Comment by Tucaen** [comment] 2018-07-10 11:09
I think the error occurs because the height of the container is calculated dynamically.
To workaround the bug I just call scrollYTo(0) on initialization.

**Comment by MurhafSousli** [comment] 2018-07-11 05:38
Hi @Tucaen can you reproduce it in a stackblitz?

**Comment by Tucaen** [comment] 2018-07-12 12:39
I'll try to, when I find the time 😇

**Comment by MurhafSousli** [comment] 2018-10-27 21:36
Closing this as cannot reproduce

**Closed by MurhafSousli** 2018-10-27 21:36 UTC
