### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IhorVimmi** [MurhafSousli/ngx-scrollbar#270] opened 2020-02-25 12:56 UTC
Hi! I've got the next error, please help me) 

ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm2015/ngx-scrollbar.js 771:59-76
 "export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
     at HarmonyImportSpecifierDependency._getErrors (/app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)

**Comment by MurhafSousli** [comment] 2020-02-25 16:48
I guess you need to install `@angular/cdk`

**Comment by IhorVimmi** [comment] 2020-02-25 19:06
> I guess you need to install `@angular/cdk`

Doesnt work with cdk 9.0.2 v! 9.0.1 is temporary fix, please check

**Comment by vpetrusevici** [comment] 2020-02-25 19:21
I have the same error for last minor angular version. In 9.00 and 9.01 no errors

**Comment by vpetrusevici** [comment] 2020-02-25 19:45
After update
![image](https://user-images.githubusercontent.com/40790510/75281392-e6eceb80-5817-11ea-9ed1-f9920b626ffa.png)
![image](https://user-images.githubusercontent.com/40790510/75281469-0ab03180-5818-11ea-9732-f56bb85baf61.png)

**Comment by MurhafSousli** [comment] 2020-02-29 19:26
Can you figure out what is causing the issue?

**Comment by MurhafSousli** [comment] 2020-02-29 19:27
I guess this is a duplicate of #272

**Closed by MurhafSousli** 2020-02-29 19:27 UTC
Labels: help wanted, need: investigation
