### ISSUE TITLE
Chrome CDK Virtual scroll keyboard navigation stucks

### ISSUE THREAD

**Issue by standby929** [MurhafSousli/ngx-scrollbar#353] opened 2021-02-18 11:02 UTC
#### Reproduction

Steps to reproduce:
1. Visit the demo page: https://ngx-scrollbar.netlify.app/ 
2. Get the "CDK Virtual Scroll Example" focused
3. Use the cursor keys to scroll down and up
4. When scrolling up it stucks after a while and have to get the list focused again to be able to scroll again with cursor keys 
 
 
#### Expected Behavior

Do not get stucked in Chrome when using cursor keys to scroll up and down (as it is working properly in Firefox).

#### Environment

- ngx-scrollbar:
- Chrome latest
- Windows 10

**Comment by MurhafSousli** [comment] 2021-04-29 10:39
That's weird, no idea! if anyone know why please let us know

**Comment by MurhafSousli** [comment] 2024-02-10 02:39
This seems to be fixed in Chrome, I am unable to reproduce it.

**Closed by MurhafSousli** 2024-02-10 02:39 UTC
Labels: help wanted, need: investigation
