### ISSUE TITLE
Conflict between PrimeNg virtual scroll p-table & ngx-scrollbar

### ISSUE THREAD

**Issue by lukaszbachman** [MurhafSousli/ngx-scrollbar#348] opened 2021-01-21 12:39 UTC
Hi,

I have a problem with a certain component which I'm building that is relying on a Table component from PrimeNG. We recently upgraded both ngx-scrollbar and Prime and that is when I started noticing the problem.

What happens is that if we embed p-table with virtual scrolling and lazy-loading into a different component which uses ngx-scrollbar, then the scrolling behavior in table is broken (jittery, not reliable, causing some artifacts to appear).

Here is how it looks, when I try to scroll with a mouse wheel inside my child component (native scrollbars):

![scrolling conflict](https://user-images.githubusercontent.com/676753/105351457-e65a0200-5bec-11eb-8934-bf4a930d4c9b.gif)

Here is a stackblitz demo:

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-b3opyc?file=src/app/app.component.html

I know that PrimeNG recently rewrote p-table component so that it uses virtual scrolling from CDK, and I also noticed your wiki article about CDK integration. But I have no control over p-table so I cannot really use this approach.

It clearly looks to me that it is related to CDK virtual scroll reusing the same DOM elements when I scroll out of the viewport. 
I was thinking that maybe it is some event propagation/bubbling causing the problem, but haven't been able to prove that.
The problem is gone as soon as I remove ngx-scrollbar from the parent, but it's still present when I just change its `[disabled]` input to `true`. 
 
#### Environment

- Angular: v10.x
- ngx-scrollbar: v7.5.3
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment] 2021-01-21 17:37
I am confused, are you trying to use ngx-scrollbar for the table, or for its parent and the scroll event issue?

Can you reproduce in a stackblitz?

**Comment by lukaszbachman** [comment] 2021-01-22 08:50
Hi @MurhafSousli,

Thanks for a reply. I was rushing this ticket a bit cause I spent half a day on chasing origins of this issue and was hoping to get some late feedback that would sprout some ideas overnight. Sorry for being sloppy!

Here is a stackblitz showing the problem. I forked the original example of PrimeNG, added latest `ngx-scrollbar` and attempted to reproduce the scenario that I'm using in my production app. I can observe exactly the same issues in this example. 

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-b3opyc?file=src/app/app.component.html

Hope that helps to point me to the right direction. Big thanks!

**Comment by MurhafSousli** [comment] 2021-04-29 11:28
This is due to the way they've implemented the virtual scroll table, I don't know why it is happening and it is outside the scope of the plugin.

It could be related to CSS or JS, but one should look at their source code to figure out how they are using the scroll event.

**Comment by MurhafSousli** [comment] 2021-07-27 21:10
@lukaszbachman I update your stackblitz with the latest version 7.6.1, can you check if the issue is fixed in this https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-t8bg7v?file=src%2Fapp%2Fapp.component.html

It seems to be working fine on my end, can you confirm?

**Comment by lukaszbachman** [comment] 2021-07-28 05:44
Hey, this seems to be working alright now! Great work! Hope to include this
in production soon, big thanks! :-)

wt., 27 lip 2021 o 23:10 Murhaf Sousli ***@***.***>
napisał(a):

**Comment by MurhafSousli** [comment] 2021-07-28 20:30
Cool! I will keep the working stackblitz for reference https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-t8bg7v

**Comment by MurhafSousli** [comment] 2024-02-23 01:25
Now it is supported in v14, https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration#primeng-table

**Closed by MurhafSousli** 2024-02-23 01:25 UTC

**Comment by lukaszbachman** [comment] 2024-02-23 08:04
> Now it is supported in v14, https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration#primeng-table

You are a star, Sir! Thank you ❤️
