### ISSUE TITLE
max-height doesn't work in ng-scrollbar

### ISSUE THREAD

**Issue by vuongquang** [MurhafSousli/ngx-scrollbar#361] opened 2021-04-02 03:14 UTC
I don't want to use specific height in ng-scrollbar.

**Comment by milchev** [comment] 2021-04-12 21:08
> I don't want to use specific height in ng-scrollbar.

I think I have found a fix for you in this thread
https://github.com/MurhafSousli/ngx-scrollbar/issues/356

**Comment by MurhafSousli** [comment] 2021-04-29 10:32
duplicate of #356

**Closed by MurhafSousli** 2021-04-29 10:32 UTC
