### ISSUE TITLE
Auto resize height not working

### ISSUE THREAD

**Issue by josineiaraujo** [MurhafSousli/ngx-scrollbar#356] opened 2021-02-25 21:30 UTC
#### Reproduction

The problem is reproduced here: https://giphy.com/gifs/adKorkj6pHRAuBdU6p/html5

Steps to reproduce:
1. Open the link 
  
#### Expected Behavior
When the accordion is expanded, the height of the window should be updated.

#### Actual Behavior
The height is updated when I adjust the window size manually.

#### Environment
- Angular: 11.2.2
- ngx-scrollbar: 7.5.4
- Browser(s): Google Chrome 88.0.4324.192
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment] 2021-02-26 01:10
Please try to reproduce it in a [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by tmushayahama** [comment] 2021-04-01 02:27
same as me, it it is not working when the height grows after ngAfterinit(). I also tried .update(), but no luck. Thanks

**Comment by milchev** [comment] 2021-04-12 21:06
Auto resize has stopped working as expected since with 7.5.0. when the option [autoHeightDisabled] was flipped to **true** by default

I have set autoHeightDisabled, autoWitdhDisabled, sensorDisabled to false.

Just do  [autoHeightDisabled]="false" and you should be fine? That worked for me.



Eventually set [sensorDisabled]="false" if needed....

I would have gone for simpler option parameter names like

height='default' or 'auto'" 
width='default' or 'auto'"

**Comment by MurhafSousli** [comment] 2021-04-29 10:31
Closing as @milchev answers the issue

**Closed by MurhafSousli** 2021-04-29 10:31 UTC
Labels: need: reproduction
