### ISSUE TITLE
Unwanted scrollbars appearing due to auto-height functionality

### ISSUE THREAD

**Issue by rooby** [MurhafSousli/ngx-scrollbar#269] opened 2020-02-19 22:27 UTC
#### Reproduction

I still haven't been able to reproduce this in stackblitz so I'm not exactly sure what is causing it on my application, however I notice that the `.ng-scroll-content` div is offset from the top of it's parent by roughly the amount that the scrollbar scrolls.

Further investigation of that shows the issue of the scrollbar appearing when it shouldn't seems to be related to this CSS:
```
.ng-scroll-content {
  display: inline-block;
}
```
If I use developer tools to toggle that to `display: block` it fixes the issue, and it then seems to stay fixed even if I toggle back to `inline-block`.
It's worth noting that nothing seems to break when this is set to `display: block`, so I'm not sure specific reason to set it to `inline-block`.

The other thing that seems to fix it is adding `vertical-align: top` to the `.ng-scroll-content` div while leaving at as `display: inline-block`.

Having said that, then I fix that issue by overriding to display: block, I still sometimes see the scrollbar briefly while it is calculating the auto-height.
In cases where have collapsible fieldsets within my content, when I expand and collapse I get flashes of scrollbars before the auto-height has updated its height value and sometimes it seems to miscalculate and the scrollbar stays until I interact with the fieldsets again.
 
#### Expected Behavior

The scrollable area is the height I have given to the parent element of the ng-scrollbar element.

I recently upgraded from 3.x to 7.1.0 and the behaviour used to be that I set the height on my container and the scrollable region was based on that.

I guess I don't really understand the purpose of this auto-height behaviour, doesn't setting the height of the scrollable region to the height of the contents of the scrollable region defeat the whole purpose of having scrollbars?

Possible solutions:

1. Use `display: block` instead of `display: inline-block` for the `.ng-scroll-content` div.
2. Use `vertical-align: top` for the `.ng-scroll-content` div. This seems a bit hacky to me compared to 1, although I'm not sure why it's inline-block in the first place.
3. Add an option to disable the auto-height functionality

I think 3 probably has to be done in addition to 1 or 2, since in the case of my expanding and collapsing fieldsets I haven't been able to find any solution that doesn't result in some unwanted scrollbars at least some of the time.

Some documentation around this behaviour in the wiki would be good too.

#### Actual Behavior

The scrollable area gets its height set to the height of the content within the parent and I can see a scrollbar even though the content doesn't fill its parent.

#### Environment

- Angular: 8.1.2
- ngx-scrollbar: 7.1.0
- Browser(s): Chrome / Edge (untested in other browsers)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by rooby** [comment] 2020-02-19 23:21
Probably duplicate of #260

**Comment by MurhafSousli** [comment] 2020-03-28 14:29
Close as duplicate of #260

**Closed by MurhafSousli** 2020-03-28 14:29 UTC
