### ISSUE TITLE
Native scrollbars are not showing when custom scrollbar is disabled

### ISSUE THREAD

**Issue by ruizmarc** [MurhafSousli/ngx-scrollbar#106] opened 2018-12-10 09:59 UTC
Hi, I'm sorry to come back with this @MurhafSousli , but I've tested it in version 3.3.3 after you closed the previous issue, but I'm getting the same problem as described in the closed issue https://github.com/MurhafSousli/ngx-scrollbar/issues/99. When disabled is true, the custom scrollbar dissapears, but the native ones are not showing.

In fact, in your demo page and in your stackblitz it is also happening. (MacOS with Safari 12 and Chrome 70)

_Originally posted by @ruizmarc in https://github.com/MurhafSousli/ngx-scrollbar/issue_comments#issuecomment-445756287_

**Comment by ruizmarc** [comment] 2018-12-10 12:10
Do you think so? If it happens to be a browser bug... I’m not sure we can really fix this. I will try to check it out and figure why this is happening. But if you arrived to the browser bug conclusion, then it will probably will be this. 

I will have a look, just in case we are missing something. I will try to do it by the end of the week ;)

 Please, let this issue open, maybe somebody can help with this :)

**Comment by MurhafSousli** [comment] 2018-12-12 20:18
It is caused by the filter pipe I added

**Comment by ruizmarc** [comment] 2018-12-12 20:30
Great! Good job finding it! Thanks for your efforts @MurhafSousli!

**Comment by MurhafSousli** [comment] 2018-12-12 20:36
Ops! I am mistaken with the issue, unfortunately that commit isn't the fix for this issue my bad.

**Comment by ruizmarc** [comment] 2018-12-14 10:52
I have just been playing around this with the stackblitz and in this example, I could manage to show the native scrollbar when disabled just commenting the line: width: calc(100% + 17px) !important;

I don't know if this may help... 

https://stackblitz.com/edit/ngx-scrollbar-fjh8oa?file=src%2Fstyles.scss

**Comment by MurhafSousli** [comment] 2018-12-15 22:43
@ruizmarc  Can you check it with version 4, it seem to be working on here https://stackblitz.com/edit/ngx-scrollbar?file=src%2Fstyles.scss

**Comment by ruizmarc** [comment] 2018-12-16 19:35
It seems it works in the link you are attaching. However, I've tried in your live demo and it is not working. We have also tested it in our own project and it is not working neither.

**Comment by MurhafSousli** [comment] 2018-12-18 15:47
@ruizmarc I just released, could this be causing the issue?

```css
::-webkit-scrollbar {
  background: transparent;
}
```
https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/scrollbar/ng-scrollbar.scss#L123-L125

**Comment by ruizmarc** [comment] 2018-12-19 05:58
I've done a test with Safari and Chrome running ngx-scrollbar without the lines you mentioned and hurray! It seems it works :D Here you have an screenshot! 

<img width="566" alt="screenshot 2018-12-19 at 05 51 41" src="https://user-images.githubusercontent.com/5717082/50201522-4cab3100-0352-11e9-873f-804662c6522b.png">

BTW, your library is improving a lot and very quick, great job and thanks for your efforts!

**Comment by MurhafSousli** [comment] 2018-12-21 02:02
Thanks @ruizmarc, couldn't have made it without the continues feedback :)

**Closed** 2018-12-21 02:02 UTC
