### ISSUE TITLE
Unable to make it work with angular 5

### ISSUE THREAD

**Issue by shahilm** [MurhafSousli/ngx-scrollbar#46] opened 2018-06-22 09:41 UTC
I have installed this for angular 5 project. The scrollbar theme appears but the scrollbar thumb doesn't move while I scroll while the scroll works on content.  

![image](https://user-images.githubusercontent.com/28943275/41770144-0a7e4d04-762f-11e8-9b3a-1ce21a9d33b7.png)

![image](https://user-images.githubusercontent.com/28943275/41769949-796a496c-762e-11e8-81fa-c7310fc0ec80.png)

**Comment by MurhafSousli** [comment] 2018-06-22 13:00
For Angular 5, `npm install ngx-scrollbar@1.5.7`

**Comment by MurhafSousli** [comment] 2018-06-22 13:01
duplicate of #43

**Closed by MurhafSousli** 2018-06-22 13:00 UTC
