### ISSUE TITLE
Scrollbar-thumb width doesn`t recalculate after change of --scrollbar-padding

### ISSUE THREAD

**Issue by meowhunter** [MurhafSousli/ngx-scrollbar#538] opened 2024-01-10 16:02 UTC
#### Reproduction

It can be reproduced on demo page https://ngx-scrollbar.netlify.app/

Steps to reproduce:
1. Open Styling options
2. Change --scrollbar-padding value
 
 
#### Expected Behavior

Scrollbar-thumb width recalculated

#### Actual Behavior

Scrollbar-thumb width stays them same and recalculates only after scroll event or resize event

#### Environment

- Angular: 16.1.5
- ngx-scrollbar: 13.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by MurhafSousli** [comment] 2024-01-10 16:09
Is there a practical use case where you want to change the padding at runtime?

**Comment by meowhunter** [comment] 2024-01-10 16:37
In my case i have table with horizontal scroll, it stays fixed at the bottom of page and takes whole page, but if i scroll to the end of table it become absolute and i need to shrink it a bit so it fits in the layout
![2024-01-10_19-32-01](https://github.com/MurhafSousli/ngx-scrollbar/assets/5663121/d0698e06-4f10-42cc-a17a-d3a1029d32c2)

when it stops at the bottom i change --scrollbar-padding value
![2024-01-10_19-33-40](https://github.com/MurhafSousli/ngx-scrollbar/assets/5663121/761649d9-aa93-44d7-a631-8271928987ab)

**Comment by MurhafSousli** [comment] 2024-01-28 12:08
Sorry, it is unclear to me, what happens when you scroll to the end? what is the expected behavior? I cannot see an issue with the screenshot provided!

**Comment by MurhafSousli** [comment] 2024-01-29 19:39
Do you mean you want to dynamically change the scrollbar thickness? because if you are using the horizontal scrollbar, the width is the calculated length while the thickness is not calculated.

But anyway, I understand that you want the scrollbar to update when you change the `--scrollbar-padding` right?

**Comment by meowhunter** [comment] 2024-01-29 21:32
> But anyway, I understand that you want the scrollbar to update when you change the --scrollbar-padding right?

Yep, that`s what i need

**Comment by MurhafSousli** [comment] 2024-02-17 13:58
This should be fixed in v14

**Closed by MurhafSousli** 2024-02-17 13:58 UTC
Labels: enhancement
