### ISSUE TITLE
Chrome and edge crashed everytime scroll.update()

### ISSUE THREAD

**Issue by thu9999** [MurhafSousli/ngx-scrollbar#432] opened 2022-03-11 08:42 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Call ngScrollbar.update() everytime the number of records inside ngScrollbar changes
2. Chrome will be crashed
 
 
#### Expected Behavior

- The scrollbar should always visible when set visibility to always
- - Browser not crashed when update scrollbar

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular: 11, 12
- ngx-scrollbar: 7.5.4, 9.0.2
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment] 2022-03-11 19:26
You did not add a reproduction for your issue!

**Comment by thu9999** [comment] 2022-03-15 05:07
I tried but it’s compiling forever.

**Comment by Jordan-Turgeon** [comment] 2022-03-17 21:11
We appear to have encountered this as well. Here are the reproduction steps for us to have this happen on Chrome:

1. Create an `ng-scrollbar` container with a smaller height
2. Have there be an `ng-for` inside this container that loops over a bunch of items
3. Have a filter bar so that you can filter the `ng-for` to not contain a scroll bar
4. Backspace out your filter to begin adding items back.
5. It should crash at the point in which a scrollbar would appear

**Comment by MurhafSousli** [comment] 2022-03-18 02:30
@Jordan-Turgeon  Could you reproduce it in a stackblitz please?

**Comment by Jordan-Turgeon** [comment] 2022-03-18 03:34
@thu9999 Did you manage to reproduce this in a simple environment? I can't seem to get it to happen just using a basic example but it's 100% reproducible and happening to us in our real application (occurred in multiple spots) that I cannot share details about.

To get around this for now I had to go through and add `[disabled]="true"` to all our `ng-scrollbar` instances to prevent this from randomly happening.

If I don't see a response before too long I can try to mock up something more complicated that resembles a spot where it does crash to see if that will make it happen when I have time.

**Comment by MurhafSousli** [comment] 2022-03-18 17:48
I reproduced it for you [here](https://stackblitz.com/edit/ngx-scrollbar-f2med4?file=src%2Fapp%2Flazy-test%2Flazy-test%2Flazy-test.component.html) and it works fine! the issue is on your end!

The scrollbar has a sensor that detects if new content has been added/removed or if content dimension changed so it updates accordingly.

If the content includes other components/directive which are triggering change detection very frequently, the scrollbar will update with it and can cause a performance issue.

That's surely a bad practice from the user side, not from the plugin. and I cannot tell what you are doing in your real application.

Here is some tips:

- Try to disable the sensor `<ng-scrollbar [sensorDisabled]="true">` 

This will prevent the scrollbar from detecting if content change, so it won't update

- Enable it again, and set a sensor debounce time `<ng-scrollbar [sensorDebounce]="100">` 

This will wait 100ms before updating the scrollbar, see if that fixes the problem.

You might want to have a look at the options in the wiki page the https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options#global-options-api-ngscrollbaroptions

I recommend you debug your app for performance issue!

You can use the **Angular DevTools** chrome plugin to check how frequently your app triggers the change detection.

***

> If I don't see a response before too long I can try to mock up something more complicated that resembles a spot where it does crash to see if that will make it happen when I have time.

The author is not supposed to reproduce your issues. Many issues turn out to be a miss use of the module, some don't read the documentation, don't look at the previously answered issues or have a problem with their project setup. but they want the author to use his own time to reproduce their issues! Your time is not more valuable than mine.

You don't need to share details about your real application! nor include complicated stuff in the reproduction, just follow the steps you provided and show it to me!

**Comment by Jordan-Turgeon** [comment] 2022-03-18 17:58
Thanks I will try that stuff.

> The author is not supposed to reproduce your issues. Many issues turn out to be a miss use of the module, some don't read the documentation, don't look at the previously answered issues or have a problem with their project setup. but they want the author to use his own time to reproduce their issues! Your time is not more valuable than mine.

I didn't mean it in this way. It just sounded like the poster had something and it was having trouble compiling on stackblitz. I did try to reproduce this with a simple example and it did not occur which might point towards it being something internal as you noted.

I just happened to look on here after identifying the issue and noticed this recent request that was very similar to what we just identified.

I was just trying to offer insight into the steps we take to trigger this every time to see if it would help. But the places this occurs are on complicated angular pages and not just a simple list views.

I appreciate the feedback and hope the real issue is within our application :).

**Comment by thu9999** [comment] 2022-03-19 13:13
Hi all,
- I'm sorry for not reproduce the issue on stackblitz as it's compiling forever when I tried.
- The correct usage in our product as follow:
+ We have a list of items which are represented in angular material table
+ The scrollbar is outside and wrap the table.
+ I set autoUpdate=true but it works randomly ( some are scrollable when the list of items changed, some did not )
+ So, I call scrollbar.update() once every time the list changed ( After table datasource changes ). Because I want the scrollbar is scrollable and visible ( the --scrollbar-thumb ).
+ And the browser crashed.
+ The issue always can be replicated in chrome and edge, but firefox.

The workaround is now to set visibility =  'always'. Despite the scrollbar-thumb never shows.
Thanks!

**Comment by thu9999** [comment] 2022-03-19 13:21
> 

Hi,
Did you try to call ngScrollbar.update() manually?

**Comment by MurhafSousli** [comment] 2022-03-19 20:43
@thu9999  I reproduced the table in stackblitz https://stackblitz.com/edit/ngx-scrollbar-e2ybha?file=src%2Fapp%2Ftable-example%2Ftable-example.html

btw, if the stackblitz is not working, try another browser or another laptop! there is nothing more I can help you with.

**Comment by thu9999** [comment] 2022-03-21 13:41
> @thu9999 I reproduced the table in stackblitz https://stackblitz.com/edit/ngx-scrollbar-e2ybha?file=src%2Fapp%2Ftable-example%2Ftable-example.html it is also working properly!
> 
> If the stackblitz is not working, try another browser or another laptop! there is nothing more I can do.

Thanks. It's not working both. I tried to created project on local and have some same settings in my project but cannot reproduce the issue.
Currently I do not call update() in my project but I will be back to this and get more details and see if there is something wrong/conflict which causes crash and will let you know.
Thank you!

**Comment by vinimaz** [comment] 2022-03-28 11:48
Maybe your problem is like mine here, I use a `position:sticky` inside a ngx-scrollbar with a lot of elements and this seems to be causing a crash in the Chromium Browsers (i.e. Edge and Chrome).

Here is the Chromium Bug Report https://bugs.chromium.org/p/chromium/issues/detail?id=1305249&q=sticky&can=2

We temporarily modified our sticky component CSS and the error seems to not happen anymore

**Comment by nguyenhmtriet** [comment] 2022-03-29 10:51
Hi guys @vinimaz @thu9999, my project just found this issue from a week ago after migrating Angular. Preceding finding this topic, we thought cause by angular v13. But it turns out, causing by ngx-scrollbar.

Luckily, I found the root cause & had a project on [stackblitz](https://stackblitz.com/edit/angular-ivy-pcwjgm?file=src/_ng-scrollbar-custom.scss).

The issue is placed at style file
`
.ngx-scrollbar-custom {
  transition: ease-out 0.5s;
}
`

Hopefully helping owner team & others to resolve this issue.

**Comment by vinimaz** [comment] 2022-03-29 11:30
Hi @nguyenhmtriet thank you for your comment. I was checking out here and after I removed the `sticky` I couldn't reproduce the error anymore. We have only two classes applied to the ngx-scrollbar with the `viewClass` as shown below:

```
<ng-scrollbar [viewClass]="'padding-left-1_5 padding-right-scrollbar'">
          <app-tree>
          </app-tree>
</ng-scrollbar>
```

And they are only

```
.padding-left-1_5 {
      padding-left: 15px;
}
.padding-right-scrollbar{
      padding-right: 15px;
}
```

So I don't think it is directly related to the cause you've found.
The `sticky` was being used inside this `app-tree` component in one sub-component.

**Comment by nguyenhmtriet** [comment] 2022-03-29 11:47
Hi @vinimaz, thank you for pointing out. On my project we resolved by either removing `sticky` or `transition` way. But I will go with the cause you found, because at least it wouldn't break our layout.

**Comment by thu9999** [comment] 2022-04-12 09:29
Hi @all 
My project does not have either <code>sticky</code> nor <code>transition</code> applied to scrollbar. 
I found that if I set config <code>visibility: ScrollbarVisibilityEnum.ALWAYS</code>, the issue will go away.
FYI.

**Comment by Jordan-Turgeon** [comment] 2022-04-15 22:06
I could also make the issue go away with removing the sticky headers or setting the visibility to `ALWAYS`. I haven't had any luck reproducing it in a Stackblitz though which bugs me because I feel like in some of our scenarios the components aren't really that complicated.

At this point I think I've tried all the things I could think of that is within our application except for trying to mock up a particular scenario that I know crashes for us using fake data or something

**Comment by DennyWeinberg** [comment] 2022-05-09 20:26
I hadthe same issue. After hours of try and error I found out that the scrollbar is the issue.

**Closed** 2022-08-07 23:30 UTC
Labels: need: reproduction
