### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by demkalkov** [MurhafSousli/ngx-scrollbar#201] opened 2019-09-06 07:42 UTC
ERROR in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
Module not found: Error: Can't resolve '@juggle/resize-observer' in '...\node_modules\ngx-scrollbar\fesm5'

**Comment by MurhafSousli** [comment] 2019-09-06 08:07
Duplicate of #185 and #197

**Closed by MurhafSousli** 2019-09-06 08:07 UTC
