### ISSUE TITLE
Cannot read property 'unsubscribe' of undefined 

### ISSUE THREAD

**Issue by naveendb92** [MurhafSousli/ngx-scrollbar#18] opened 2018-02-28 19:21 UTC
I saw that this bug was closed. But still, I face the same issue. Tried a lot but didn't find the solution.

Kindly help me with this.

![image](https://user-images.githubusercontent.com/29221698/36808242-8e10a70a-1cea-11e8-988e-2524292de546.png)

**Comment by MurhafSousli** [comment] 2018-02-28 22:44
Can you reproduce the issue https://stackblitz.com/edit/ngx-scrollbar

**Comment by asfo** [comment] 2018-03-08 23:53
I have this issue too.

I can't reproduce it in StackBlitz but this is what happens:

I have a redirect from the URL '/login' to '/dashboard' in case the user is logged in...

This issue happens when I go to the URL '/404' and I click on "Return to home" (a [routerLink]) to the '/login' URL, so in this URL as I said if the user is logged in this redirects to the '/dashboard'.

But when this process happens, this issue is thrown...

![image](https://user-images.githubusercontent.com/829964/37182949-619f378a-22f9-11e8-924c-bf1e945405df.png)

**Comment by MurhafSousli** [comment] 2018-03-09 05:14
This is fixed in v1.5.6

**Closed** 2018-03-09 05:16 UTC
Labels: bug
