### ISSUE TITLE
Scroll appears when it should not

### ISSUE THREAD

**Issue by Nekronik** [MurhafSousli/ngx-scrollbar#260] opened 2020-01-16 10:59 UTC
#### Reproduction
[StackBlitz](https://stackblitz.com/edit/ngx-scrollbar-full-height) reproduction.

Steps to reproduce:
1. Scroll up and down
2. body has a red background to make it obvious
 
#### Expected Behavior

For a 100vh viewport height with a 100vh content height no scroll should appear

#### Actual Behavior

Scroll is happening

#### Environment

- Angular: 8.2.14
- ngx-scrollbar: 7.1.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): KDE Neon (Ubuntu)

Feel free to give the issue a better name

**Comment by MurhafSousli** [comment] 2020-02-10 01:41
Cannot really figure out the cause probably from the layout.. if anyone catches it please let me know!

**Comment by MurhafSousli** [comment] 2020-02-16 16:59
@p3x-robot can you try giving your element (the direct child of ng-scrollbar) `display: block` and see if it works out?

**Comment by MurhafSousli** [comment] 2020-02-16 20:35
I tried to look into the issue, but it is still unclear. why is the extra tiny height added to the container height! even when I log the height of the scrollbar component, the viewport wrapper, the content wrapper, and child element heights.. they are all the same! so how could it is still be scrollable! 

Currently using flexbox partially fix the problem
```scss
::ng-deep {
  .ng-scroll-viewport {
    display: flex;
    flex-direction: column;
  }
  .ng-scroll-content {
    flex: 1;
  }
}
```

https://stackblitz.com/edit/ngx-scrollbar-full-height-h9k1kc?file=src%2Fapp%2Fapp.component.ts

**Comment by MurhafSousli** [comment] 2020-02-17 12:45
Not sure if that will work out, the scrollbar has so many use cases, one should be very careful in modifying those styles, they could ruin other use cases.

**Comment by MurhafSousli** [comment] 2020-02-17 14:11
Let's keep it open for a while

**Comment by Nekronik** [comment] 2020-02-18 06:25
Hello @MurhafSousli

At first I thought it was related to `margin-block` but it did no change when modifying it.

I believe this issue is related to the scroll-content wrapper being an inline like element.
This [stackoverflow](https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image) explains it better.

Setting `vertical-align: middle` to the `.ng-scroll-content` fixes my use case too.

@p3x-robot could you also check if that fixes your use case?

**Comment by rooby** [comment] 2020-02-19 22:42
Oops sorry, I just realised that maybe my issue #269  is a duplicate of this one.

My investigations also led me to 
```
.ng-scroll-content {
  display: inline-block;
}
```
Setting to one of these:

```
.ng-scroll-content {
  display: block;
}
```
or
```
.ng-scroll-content {
  display: inline-block;
  vertical-align: top;
}
```
Seemed to fix it for me also, however I still got inconsistent results, especially where I had content  in my scrollable area that changed height, like collapsible fieldsets.

It would be good if we could disable the auto-height  functionality all together.

**Comment by rooby** [comment] 2020-02-19 23:19
Regarding @MurhafSousli 's comment

> can you try giving your element (the direct child of ng-scrollbar) display: block and see if it works out?

In my case, the direct child is already using display: block.

**Comment by MurhafSousli** [comment] 2020-03-28 14:28
Generally, the current styles are the best I could come with to serve all use cases, I cannot change a style of a wrapper before it is confirmed that it works for other uses cases.. such as using with virtual scroll and the examples listed in the demo app.

**Comment by rooby** [comment] 2020-03-28 22:34
Regardless of any CSS changes that might help fix this, would you be OK with adding an option to disable the auto height feature?
Happy to split that to a separate issue if you like.

**Comment by PierreDuc** [comment] 2020-05-12 10:28
A couple of findings:

Using fixed height (100px, 100vh) makes it appear unless you hover over it with the mouse. This is because the `updateState` is called in the `ngAfterViewChecked` and for some reason the `clientHeight` is 0 at the point of the first call. Putting it in a `setTimeout` makes it work. (This feels like a different issue, and is perhaps just on my browser, or a stackblitz issue)

By using 100vh the scrollbar appears because the `scrollHeight` is 4px higher than the `clientHeight`. If you use `font-size: 0;` it works like above. This is also more or less a non issue, because once you add a text node, the extra 4px [disappears](https://stackblitz.com/edit/ngx-scrollbar-full-height-ec6mpm?file=src%2Fapp%2Fapp.component.html). I tried to look into the spec but couldn't find any reason why this should happen.

**Comment by lozah** [comment] 2020-06-10 00:10
> A couple of findings:
> 
> Using fixed height (100px, 100vh) makes it appear unless you hover over it with the mouse. This is because the `updateState` is called in the `ngAfterViewChecked` and for some reason the `clientHeight` is 0 at the point of the first call. Putting it in a `setTimeout` makes it work. (This feels like a different issue, and is perhaps just on my browser, or a stackblitz issue)

I got this problem on my project. I have a container with the scrollbar which is not displayed at first. But then after displaying the scrollbar appears even if there is enough space. Then it disappears when you hover over it.

Check this stackblitz I took from an other issue and updated for this case. (go to page comparision, click on the click button)
[stackblitz](https://stackblitz.com/edit/ngx-scrollbar-compare-native-auto-height-f7ax8n)

Is there a fast way of fixing this ?

**Comment by lozah** [comment] 2020-06-10 00:19
> A couple of findings:
> 
> Using fixed height (100px, 100vh) makes it appear unless you hover over it with the mouse. This is because the `updateState` is called in the `ngAfterViewChecked` and for some reason the `clientHeight` is 0 at the point of the first call. Putting it in a `setTimeout` makes it work. (This feels like a different issue, and is perhaps just on my browser, or a stackblitz issue)

Hello, I got this problem on my project. I have this container which at first is not displayed. But when it is displayed with height based on viewport the scrollbar appears even if there is enough space. The scrollbar disappears when you hover over it as you mentionned.

I took a stackblitz from a previous issue to illustrate (go to page comparision then click on the click button) [stackblitz](https://stackblitz.com/edit/ngx-scrollbar-compare-native-auto-height-f7ax8n)

Can the fix with the timeout be applied in a futur version ?

**Comment by maiertudor** [comment] 2020-07-07 12:05
@lozah 

> Hello, I got this problem on my project. I have this container which at first is not displayed. But when it is displayed with height based on viewport the scrollbar appears even if there is enough space. The scrollbar disappears when you hover over it as you mentionned.

I took a stackblitz from a previous issue to illustrate (go to page comparision then click on the click button) stackblitz

I have exactly the same problem, in order to solve it I called the scrollbarRef.update() method in ngAfterViewInit.

**Comment by kGk13** [comment] 2020-08-24 08:42
> Hello @MurhafSousli
> 
> At first I thought it was related to `margin-block` but it did no change when modifying it.
> 
> I believe this issue is related to the scroll-content wrapper being an inline like element.
> This [stackoverflow](https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image) explains it better.
> 
> Setting `vertical-align: middle` to the `.ng-scroll-content` fixes my use case too.
> 
> @p3x-robot could you also check if that fixes your use case?

This fix worked for me.

**Comment by MurhafSousli** [comment] 2020-11-14 07:44
I am wondering if this issue still exist in the new version v3.7.4, can you try to comment out the workaround and see if it still happens?

**Comment by MurhafSousli** [comment] 2020-11-14 09:24
No worries

**Closed by MurhafSousli** 2020-11-14 09:24 UTC
Labels: help wanted
