### ISSUE TITLE
ngx-scrollbar scroll offset isn't synchronized with CDK-virtual scroll and cause unnecessary

### ISSUE THREAD

**Issue by yarinsa** [MurhafSousli/ngx-scrollbar#379] opened 2021-06-02 13:47 UTC
#### Reproduction

I have tried to reproduce with no success (stackblitz says that cdk-virtual-scroll-viewport is now a known element) but I will do my best to provide a detailed explanation.
I have a complex list with items that have a different height and rendered in a virtual scroll. I wrote my own virtual scroll strategy to handle this. When the user navigates out of the view using `arrow-up / arrow-down`, I calculate the next scroll offset and scroll manually. My logic seems right, as when I am putting breakpoint right after it looks great. A few ms afterward this function runs and changes the scroll position again. It's not consistent but it does happen at the same point every time.
 
I was able to catch what I think is the issue (it's a tricky one to debug) After scrolling **the offset of the viewport and the offset in ngx-scrollbar.js isn't synchronized.** (Those screenshots were taken after performing the same scroll action, so I would expect the numbers to match).

##### Step 1 (Performing scroll):
(BTW calling `this.scrollbarRef.scrollTo({ top: nextOffset })` has the same result)

<img width="381" alt="Screen Shot 2021-06-02 at 16 21 49" src="https://user-images.githubusercontent.com/44482362/120489832-9bcd6b00-c3c0-11eb-93e8-be27cc995984.png">

##### Step 2 (right after the previous call, before`animationFrameScheduler` is getting called, looks goos):

<img width="1000" alt="Screen Shot 2021-06-02 at 16 41 18" src="https://user-images.githubusercontent.com/44482362/120491112-a50b0780-c3c1-11eb-9282-ed15f053fc04.png">

##### Step 3 (after `animationFrameScheduler` was called):

<img width="850" alt="Screen Shot 2021-06-02 at 16 19 17" src="https://user-images.githubusercontent.com/44482362/120490003-b9023980-c3c0-11eb-9694-c1234add1686.png">

 
#### Expected Behavior

Don't do anything after scroll, meaning the frame will end up like this.
<img width="997" alt="Screen Shot 2021-06-02 at 16 38 00" src="https://user-images.githubusercontent.com/44482362/120490261-ee0e8c00-c3c0-11eb-9456-07c4240ee5e8.png">

#### Actual Behavior

ngx-scrollbar changes my scroll position and put a wrong scroll offset. 
<img width="990" alt="Screen Shot 2021-06-02 at 16 37 49" src="https://user-images.githubusercontent.com/44482362/120490366-054d7980-c3c1-11eb-84b2-e34e2861d3a4.png">

#### Environment

- Angular: ~11.2.9
- ngx-scrollbar: ^7.5.4
- Browser(s): Electron (chromium)
- Operating System: reproduce on macOS and Windows, Ubunto wasn't checked

**Comment by MurhafSousli** [comment] 2021-07-25 01:04
@yarinsa I could not reproduce your issue and you didn't add a reproduction to help debug it, but anyway, I released a new version and now it update differently with the CDK virtual scroll, please let me know if the issue is resolved with v7.6.0

**Comment by yarinsa** [comment] 2021-07-26 03:58
Thank you! Will update soon and let you know

**Comment by MurhafSousli** [comment] 2021-08-04 01:02
Closing... feel free to reopen if you still have the issue

**Closed by MurhafSousli** 2021-08-04 01:02 UTC
