### ISSUE TITLE
Content hidden on Ivy 9.0.0-rc4

### ISSUE THREAD

**Issue by mickz18** [MurhafSousli/ngx-scrollbar#253] opened 2019-12-04 13:47 UTC
#### Reproduction

Steps to reproduce:
1. Create App with cli `npx -p @angular/cli@next ng new`
2. Add @angular/cdk@next & ngx-scrollbar
3. Import module NgScrollbarModule 
4. wrap div content with <ng-scrollbar></ng-scrollbar>
 
#### Expected Behavior

See content and new scrollbar

#### Actual Behavior

Scrollbar show with correct size but content is hidden (but present).
Content is  still visible when no scrollbar are needed.

#### Environment

- Angular: 9.0.0-rc.1 -> 9.0.0-rc.4
- ngx-scrollbar: 7.1.0
- Browser(s): chrome & firefox
- Operating System: Linux

Working if Ivy are disabled so may be angular team should fix it.

**Comment by MurhafSousli** [comment] 2019-12-12 23:29
Duplicate of #217

**Closed by MurhafSousli** 2019-12-12 23:29 UTC
